
apiVersion: apps/v1

kind: Deployment

metadata:
  annotations:
  labels:
    app: {{ .Values.AppName }}
  name: {{ .Values.AppName }}
  namespace: {{ .Values.namespace.name }}
  
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
        app: {{ .Values.AppName }}
  strategy:
    rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.AppName }}
    
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Values.AppName }}
        
        ports:
        - containerPort: 3111
          protocol: TCP
        
        livenessProbe:
           httpGet:
             path: {{ .Values.livenessProbe.path }}
             port: {{ .Values.livenessProbe.port }}
           initialDelaySeconds: 30
           periodSeconds: 3
        readinessProbe:
           httpGet:
             path: {{ .Values.livenessProbe.path }}
             port: {{ .Values.livenessProbe.port }}
           initialDelaySeconds: 30
           periodSeconds: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
            
          limits:
            memory: "128Mi"
            cpu: "500m"
