apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.AppName }}
  name: {{ .Values.AppName }}
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
    - port: 4111
      protocol: TCP
      targetPort: 3111
  selector:
    app: {{ .Values.AppName }}
  type: ClusterIP
